# GitHub Actions docs
# https://help.github.com/en/articles/about-github-actions
# https://help.github.com/en/articles/workflow-syntax-for-github-actions
name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
    - name: Use Node.js 16.10
      uses: actions/setup-node@v2
      with:
        node-version: 16.10
    - name: Install dependencies
        run: npm install
    - name: Lint
        run: npm run lint
    - name: Format code
        run: npm run format
    - name: Run tests
        run: npm test